### ISSUE TITLE
[pin] Git should be installed at a specific revison

### ISSUE THREAD

**Issue by gozer** [mozilla-it/nubis-tlscanary-mozilla-org#16]
All packages, really. using ensure=>latest means we don't actually know what
got installed, and we can't reliably rebuild an older image.

**Comment by danielhartnell** [comment]
@gozer,

Agreed. I can take ownership of this, identify the current package that's used, and pin that. Did you have a specific package version in mind?

**Comment by gozer** [comment]
Nope! As long as Its pinned at some version

**Comment by danielhartnell** [comment]
Merged topic branch into master. Pinned package to the one that was currently installed, 1:1.9.1-1ubuntu0.3. Rebuilding AMI in Jenkins now. I'll re-open this issue if the build fails.

https://github.com/mozilla-it/nubis-tlscanary-mozilla-org/blob/master/nubis/puppet/git.pp

**Comment by danielhartnell** [comment]
Remaining OS agnostic makes sense. I've noted this for my future contributions. I think it's reasonable to mark this issue as solved once again since PR #20 was merged. Feel free to open it back up if needed!
