### ISSUE TITLE
Website content is not updating in prod deployments

### ISSUE THREAD

**Issue by danielhartnell** [mozilla-it/nubis-tlscanary-mozilla-org#31]
**Summary:**

For Planet and TLS Canary, we have cron jobs to automatically update website content. It looks like these cron jobs are failing to perform their job successfully.

**Supporting evidence:**

https://www.tlscanary-stage.stage.us-west-2.tlscanary.nubis.allizom.org/
https://www.tlscanary-prod.prod.us-west-2.tlscanary.nubis.allizom.org/

As you can see, the date of the latest run is different for each deployment. I suspect that the newest run in prod corresponds to when the AMI build process completed.

**Troubleshooting:**

I'll start by looking into the following:

* Outbound network connectivity in production environment
* Cron job configuration differences between prod and stage

**Comment by gozer** [comment]
```shell
tlscanary> bash -x /usr/local/bin/nubis-update-site
+ REPO_DIR=/var/lib/ssl_compat
+ SOURCE_REPO=https://github.com/mwobensmith/ssl_compat.git
+ DEPLOY=0
+ '[' '!' -d /var/lib/ssl_compat/.git ']'
+ cd /var/lib/ssl_compat
+ /usr/bin/git remote update
Fetching origin
++ /usr/bin/git rev-parse master
+ LOCAL_REV=8ec9c4b2d6971acc1335496a8ea27471b347c8f8
++ /usr/bin/git rev-parse origin/master
+ REMOTE_REV=1dd71f05f0dd4c967f1a20aeba332367e5682cb4
+ '[' 8ec9c4b2d6971acc1335496a8ea27471b347c8f8 '!=' 1dd71f05f0dd4c967f1a20aeba332367e5682cb4 ']'
+ /usr/bin/git pull
Updating 8ec9c4b..1dd71f0
error: Your local changes to the following files would be overwritten by merge:
	main.sh
	main2.sh
	ssl_site_finder.sh
Please, commit your changes or stash them before you can merge.
Aborting
+ cleanup
+ cd /var/lib/ssl_compat
+ /usr/bin/git describe --always --tags --dirty
+ find /var/lib/ssl_compat -type d '!' -perm 0755 -exec chmod 0755 '{}' ';'
+ find /var/lib/ssl_compat -type f '!' -perm 0644 -exec chmod 0644 '{}' ';'
+ DEPLOY=1
+ '[' 1 == 1 ']'
+ /usr/local/bin/atomic-rsync -a --cvs-exclude --delete /var/lib/ssl_compat/ /var/www/html/
```

```shell
tlscanary> git -C /var/lib/ssl_compat status
On branch master
Your branch is behind 'origin/master' by 26 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   main.sh
	modified:   main2.sh
	modified:   main_temp.sh
	modified:   ssl_site_finder.sh
	modified:   test_profile/times.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	_revision.txt

no changes added to commit (use "git add" and/or "git commit -a")
```
```shell
tlscanary> git -C /var/lib/ssl_compat diff
diff --git a/main.sh b/main.sh
old mode 100755
new mode 100644
diff --git a/main2.sh b/main2.sh
old mode 100755
new mode 100644
diff --git a/main_temp.sh b/main_temp.sh
old mode 100755
new mode 100644
diff --git a/ssl_site_finder.sh b/ssl_site_finder.sh
old mode 100755
new mode 100644
diff --git a/test_profile/times.json b/test_profile/times.json
old mode 100755
new mode 100644
```

**Comment by gozer** [comment]
Looks more like the git checkout is not clean, so can't cleanly pull...

**Comment by danielhartnell** [comment]
`cleanup()` is called after `git pull`. The cleanup process changes the file modes which puts us into a state ahead of master and we cannot pull. Since we can't pull, we end up further and further out of date over time. You can see that we are 26 commits behind master. I don't think the untracked file, `_revision.txt`, is terribly problematic and I think we can get away with issuing our `chmod` calls against the files in the web root rather than this git repository.

https://github.com/mozilla-it/nubis-tlscanary-mozilla-org/blob/master/nubis/puppet/files/update-site.sh#L39

I'll make the appropriate changes and test it out.

**Comment by floatingatoll** [comment]
Why are we doing these two commands? The git repo should already have these
permissions checked in, and will enforce them on checkout, so making
alterations here is not helping us any.

+ find /var/lib/ssl_compat -type d '!' -perm 0755 -exec chmod 0755 '{}' ';'
+ find /var/lib/ssl_compat -type f '!' -perm 0644 -exec chmod 0644 '{}' ';'
